# This is a basic workflow to help you get started with Actions
name: BUILD

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install deps
        run: npm install

      - name: Run lint
        run: npm run lint -- --no-fix

      - name: Run tests
        run: npm run test:unit

      - name: Build
        run: npm run build

      - name: Create Artifact
        run: |
          cd ./dist
          zip -r fluidd.zip ./
          cd ..

      - name: Copy output
        run: cp ${{ github.workspace }}/dist/fluidd.zip fluidd-latest.zip

      - uses: actions/upload-artifact@v2.2.4
        with:
          name: fluidd-latest.zip
          path: fluidd-latest.zip
